mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views as mysite_views


urlpatterns = [
    path("", mysite_views.default_index, name='default_index'),
    path('write/', mysite_views.write_value, name='write_value'),
    path('read/', mysite_views.read_value, name='read_value'),
    path('show_json/', mysite_views.show_json, name='show_json'),
    path('download_img/', mysite_views.download_img, name='download_img'),
    path('download_iso/', mysite_views.download_iso, name='download_iso'),
    path('download/<int:file_type>/', mysite_views.download_file, name='download_file'),
    path("polls/", include("polls.urls")),
    path("parts/", include("parts.urls")),
    path('users/', include("users.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/parts/urls.py
from django.urls import path, reverse
from . import views, pdf_view, filter_views, humanize_views as hm_views
from . import filter_custom, tags_custom_views

app_name = "parts"

urlpatterns = [
    path('', views.index, name='index'),
    path("upload_file/", views.user_upload_file, name='user_upload_file'),
    path("upload_success/", views.upload_success, name="upload_success"),
    path("upload_fail/", views.upload_fail, name="upload_fail"),

    path("make_csv/", views.make_csv, name='make_csv'),
    path("make_large_csv/", views.some_streaming_csv_view, name="make_large_csv"),
    path("make_csv_by_t/", views.make_csv_by_template, name="make_csv_by_template")
]

# pdf_view相关url配置
urlpatterns += [
    path('pdf_io/', pdf_view.pdf_by_io, name='pdf_by_io'),
    path('pdf_res/', pdf_view.pdf_by_response, name='pdf_by_response'),
]

# filter_views.py相关url配置
urlpatterns += [
    path('show_filter/', filter_views.show_filter, name='show_filter')
]


# filter_views.py相关url配置
urlpatterns += [
    path('show_humanize/', hm_views.humanize_show, name='show_filter')
]

# filter_custom.py 相关url配置
urlpatterns += [
    path("filter_custom/", filter_custom.filter_custom_show, name='filter_custom')
]

# tags_custom.py相关url配置
urlpatterns += [
    path("tags_custom/", tags_custom_views.show_tags_custom, name='show_tags_custom'),
]

mysite/polls/urls.py
from django.urls import path, re_path, register_converter
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views, urls_converters, template_view
from . import form_views

register_converter(urls_converters.FourDigitYearConverter, 'yyyy')

# 定义app_name可用于动态调用url path的name,
# 但是定义之后就不能单独使用url path的name获取url
app_name = "polls"

urlpatterns = [
    path('', views.index, name='index'),
    #
    # # 使用参数.格式1
    # path('bio/<username>', views.bio, name='bio'),
    # # 限制参数类型
    # path('num/<int:num>', views.num, name='num'),
    #
    # # 使用正则定义url参数
    # re_path('bio2/(?P<username>\w+)/$', views.bio2, name='bio2'),
    #
    # # 例： /polls/5/
    path("<int:question_id>/", views.detail, name='detail'),
    # 例： /polls/5/result/
    path("<int:question_id>/results/", views.results, name='results'),

    path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # 例: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name='vote'),

    path("<yyyy:year>/question/", views.show_year_question, name='year_question'),
    re_path(r"^(?P<year>[0-9]{4})/year_question/$", views.show_year_question, name='year_question_two'),
    path("question_list/", views.quesiton_list, name='quesiton_list'),
]


urlpatterns += [
    path('tview/', template_view.jinja2_by_template, name='template_view'),
    path('tview1/', template_view.index_1, name='template_index_1'),
    path('tview2/', template_view.index_2, name='template_index_2'),
    path('show_base/', template_view.show_base, name='show_base'),
    path('use_base/<int:num>/', template_view.use_base, name='use_base'),
]


# form_views.py相关配置
urlpatterns += [
    path('form_show/', form_views.form_show, name='form_show'),
    path('login_success/', form_views.form_login_success, name='login_success'),
    path("form_field/", form_views.form_field_show, name='form_field_show'),
]

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('发布时间')

    def __str__(self):
        """
        把question_text的值当做实例转为字符串的结果
        :return:
        """
        return self.question_text

    def was_published_recently(self):
        """
        Question的发布时间是否为1天之内，是则返回True,否则返回False
        发布时间若晚于当前时间。也会返回False
        :return:
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    # 设定点击后台列表中的方法时的排序字段
    was_published_recently.admin_order_field = 'pub_date'
    # 控制列表中字段标题列的显示内容
    was_published_recently.short_description = '是否最近发布?'
    # 控制bool型的值是否使用django的bool样式
    was_published_recently.boolean = True


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/polls/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, required=True, min_length=6,
                               label="账号", help_text="账号为6-20位长的字符串")
    password = forms.CharField(max_length=20, required=True, min_length=6,
                               label="密码", widget=forms.PasswordInput(),
                               )


class TestForm(forms.Form):
    is_true = forms.BooleanField(required=False)
    username = forms.CharField(strip=True, empty_value='xxx')
    password = forms.CharField(required=False, widget=forms.PasswordInput())
    hid_2 = forms.CharField(required=False, widget=forms.HiddenInput())
    age = forms.IntegerField(required=False, max_value=100, min_value=6)
    hid_1 = forms.CharField(required=False, widget=forms.HiddenInput())
    type_1 = forms.ChoiceField(required=False, choices=(("", "请选择"), (1, "一"), (2, "二"), (3, "三")))
    email = forms.EmailField(required=False, )
    height = forms.IntegerField(required=False, )
    birthday = forms.DateField(required=False, )
    birthday_full = forms.DateTimeField(required=False, )
    birthday_time = forms.TimeField(required=False, )
    detail = forms.CharField(required=False, widget=forms.Textarea(attrs=dict(rows=5, cols=30)))
    # hobby_one = forms.CharField(widget=forms.CheckboxInput())
    hobby = forms.CharField(required=False, widget=forms.CheckboxSelectMultiple(choices=((1, "吃"), (2, "喝"), (3, "玩"), (4, "学习"))))
    sex = forms.CharField(required=False, widget=forms.Select(choices=(("", "请选择"), ('1', "男"), (0, "女"))))
    is_rich = forms.NullBooleanField(required=False, widget=forms.NullBooleanSelect())
    hobby_2 = forms.CharField(required=False, widget=forms.SelectMultiple(choices=((1, "吃"), (2, "喝"), (3, "玩"), (4, "学习"))))
    food_hobby = forms.CharField(required=False, widget=forms.RadioSelect(choices=((1, "吃"), (2, "喝"), (3, "玩"), (4, "学习"))))

    portrait = forms.FileField(required=False, allow_empty_file=True)

    join_time = forms.CharField(widget=forms.SelectDateWidget(
        years=(2007, 2009),
        months={"": "请选择", "1": "一月", "2": "二月"},
        empty_label=("9", "10", "11")
    ))

mysite/polls/views.py
from django.shortcuts import redirect, render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponseNotFound
from django.urls import reverse
from .models import Question, Choice
from django.views import generic
from django.utils import timezone
import json
from django.views.decorators.http import require_http_methods


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'lasted_question_list'

    def get_queryset(self):
        # pub_date__lte=timezone.now() 是判断pub_date小于等于当前时间
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def index(request):
    # polls的默认页面。会显示待投票的问题的列表.
    lastest_question_list = Question.objects.order_by("-pub_date")[:5]

    # 较为简单的使用模板文件的方式
    context = {
        "lasted_question_list": lastest_question_list
    }
    response = render(request, 'polls/index.html', context, using='django')
    return response


def bio(request, username):
    return HttpResponse("Hello, %s" % username)


def num(request, num):
    return HttpResponse("number is %s" % num)


def bio2(request, username):
    return HttpResponse("bio2's username=%s" % username)


def detail(request, question_id):
    print("this is detail page")
    if request.session.get("loginuser"):
        print('username=', request.session['loginuser'])
    else:
        print("未登录")

    print("site=", request.site)
    # question = get_object_or_404(Question, pk=question_id)
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("您查找的这个问题并不存在。请确认您传入的问题编号是否正确")
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    print(request.META['QUERY_STRING'])
    print(request.META['SERVER_NAME'])
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {'question': question})


def vote(request, question_id):
    print("xxxxxxxxxxxxxx")

    print(request.POST)

    for k in request.POST:
        print("%s=%s" % (k, request.POST[k]))
    print("request.FILES")
    print(request.FILES)

    print("request.META=")
    print(request.META)
    for k, v in request.META.items():
        print('%s=%s' % (k, v))
    # get_object_or_404 抛出的404不能自定义提示内容。
    question = get_object_or_404(Question, pk=question_id)
    try:
        # request.POST可以获取到所有表单提交的数据
        if request.method == "POST":
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {
            'question': question,
            'error_message': "您投票的选项不存在或不正确"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # HttpResponseRedirect可以跳转到指定地址
        # reverse方法可以获取指定url name的地址
        return HttpResponseRedirect(reverse('polls:results', args=(question.id, )))


def show_year_question(request, year):
    questions = Question.objects.filter(pub_date__year=year)
    return render(request, "polls/year_question.html",
                  {'question_year': questions})


def quesiton_list(request):
    for k, v in request.GET.items():
        print('%s=%s' % (k, request.GET.get(k)))

    print("POST")
    print(request.POST)


    datas = [dict(id=obj.id,
                  question_text=obj.question_text,
                  pub_date=obj.pub_date.strftime('%Y-%m-%d %H:%M:%S'))
             for obj in Question.objects.filter(pub_date__year=2017)]

    result = json.dumps(datas)
    # 下载文件所需的content_type设置
    # response = HttpResponse(result, content_type="application/octet-stream")
    # 注意：绝大多数情况下不要设置为301.否则用户浏览器可能会缓存此次设置。
    # 导致用户得不到服务器最新的修改
    response = HttpResponse(result)
    # return response
    # return redirect("/polls/")
    # question = get_object_or_404(Question, id=1)
    # question_list = get_list_or_404(Question, id__lt=0)
    return response

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} 这里现在是base模板的标题 {% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    {% block css %}
    {% endblock %}
</head>
<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">主页</a> </li>
            <li><a href="/polls/">投票</a> </li>
        </ul>
        {% endblock %}
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>


</body>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
{% block js %}
{% endblock %}
</html>

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }} </strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <!--label 标签的for指定一个id,点击label的文字时。会选中对应的待选项-->
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br />
    {% endfor %}
    上传文件：<input type="file" name="test_up_file" />

    <input id="submit" type="submit" value="投票" />
</form>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />



{% if lasted_question_list %}
    <ul>
        <!--推荐的用法-->
        {% for question in lasted_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}" >{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>没有待投票的问题</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text}} -- {{ choice.votes }} vote {{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">我还要再投一次</a>

mysite/polls/templates/polls/t_index.html
{% if page_name %}
   this is test render   {{ page_name }}
{% else %}
这啥啊别闹页面不对
{% endif %}


{% if user_info %}
用户名是: {{ user_info.userid }}
昵称是: {{ user_info.nickname }}

xxxx: {{ list_0.1 }}

{% endif %}

<br  clear="both" />
<ul>
    {% for i in num_list %}
    <li style="color: {% cycle 'green' 'red' 'gray' %} ;" >now number ={{ i }}</li>
    {% endfor %}
</ul>

<br />

{{ "oh , please give me your heart~"|title }}



<br />
日期： {{ login_time|date:"Y-m-d" }}
完整日期：{{ login_time|date:'Y-m-d H:i:s' }}

mysite/polls/templates/polls/use_base_1.html
 {% extends "polls/base.html" %}

{% block title %} 我不管。我就要改成{% block title_name %} use_base_1 {% endblock %}的title {% endblock %}

{% block sidebar %}

<ul>
    {% for k, v in dict_0.items %}
    <li>{{ k }}={{ v }}</li>
    {% endfor %}

    {% for v in dict_0.values %}
    <li>{{ v }}</li>
    {% endfor %}

    {% for num in num_list %}
    <li>this num is {{ num }}</li>
    {% endfor %}
</ul>
{% block hahaha %}
  我终于天下无敌啦~
{% endblock %}
{% endblock %}

mysite/polls/templates/polls/use_base_2.html
{% extends "polls/use_base_1.html" %}
{% block title_name %} use_base_2 {% endblock %}
{% block hahaha %}
  我不, {% firstof is_red is_black is_yellow   %}


{% filter upper|lower|upper %}
AbCddEfG
{% endfilter %}


<br />

<ul>
{% for num in num_list %}
    <li> this is {{ num }}, {% ifchanged num  %} 这次与上次不同 {% else %} 这次啊。就没变 {% endifchanged %} </li>
{% endfor %}
</ul>



<a href="{% url 'polls:index' %}" target="_blank">打开新页面</a>
<a href="{% url 'polls:detail' 1 %}" target="_blank">打开新页面</a>
{% endblock %}

mysite/polls/templates/polls/year_question.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if question_year %}
    <ul>
        <!--推荐的用法-->
        {% for question in question_year %}
        <li><a href="{% url 'polls:detail' question.id %}" >{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>指定年份没有待投票的问题</p>
{% endif %}