mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views as mysite_views


urlpatterns = [
    path("", mysite_views.default_index, name='default_index'),
    path('write/', mysite_views.write_value, name='write_value'),
    path('read/', mysite_views.read_value, name='read_value'),
    path('show_json/', mysite_views.show_json, name='show_json'),
    path('download_img/', mysite_views.download_img, name='download_img'),
    path('download_iso/', mysite_views.download_iso, name='download_iso'),
    path('download/<int:file_type>/', mysite_views.download_file, name='download_file'),
    path("polls/", include("polls.urls")),
    path("parts/", include("parts.urls")),
    path('users/', include("users.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/parts/urls.py
from django.urls import path, reverse
from . import views, pdf_view, filter_views, humanize_views as hm_views
from . import filter_custom, tags_custom_views

app_name = "parts"

urlpatterns = [
    path('', views.index, name='index'),
    path("upload_file/", views.user_upload_file, name='user_upload_file'),
    path("upload_success/", views.upload_success, name="upload_success"),
    path("upload_fail/", views.upload_fail, name="upload_fail"),

    path("make_csv/", views.make_csv, name='make_csv'),
    path("make_large_csv/", views.some_streaming_csv_view, name="make_large_csv"),
    path("make_csv_by_t/", views.make_csv_by_template, name="make_csv_by_template")
]

# pdf_view相关url配置
urlpatterns += [
    path('pdf_io/', pdf_view.pdf_by_io, name='pdf_by_io'),
    path('pdf_res/', pdf_view.pdf_by_response, name='pdf_by_response'),
]

# filter_views.py相关url配置
urlpatterns += [
    path('show_filter/', filter_views.show_filter, name='show_filter')
]


# filter_views.py相关url配置
urlpatterns += [
    path('show_humanize/', hm_views.humanize_show, name='show_filter')
]

# filter_custom.py 相关url配置
urlpatterns += [
    path("filter_custom/", filter_custom.filter_custom_show, name='filter_custom')
]

# tags_custom.py相关url配置
urlpatterns += [
    path("tags_custom/", tags_custom_views.show_tags_custom, name='show_tags_custom'),
]

mysite/parts/models.py
from django.db import models

# Create your models here.

mysite/parts/views.py
import os
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.http import StreamingHttpResponse
from django.urls import reverse
from django.conf import settings
import random
import csv
from django.template import loader, Context


class TestClass:
    pass

def index(request):
    return HttpResponse("this is parts index")


def handle_uploaded_file(file_obj, ext):
    now = timezone.now()
    filename = "%s%s%s%s%s%s%s%s%s" % (
        now.year, now.month, now.day, now.hour, now.minute, now.second,
        now.microsecond, random.randint(100000, 999999), ext)
    file_path = os.path.join(settings.USER_UPLOAD_DIR, filename)

    with open(file_path, 'wb+') as f:
        for chunk in file_obj.chunks():
            f.write(chunk)


def user_upload_file(request):
    if request.method == "POST":
        files = request.FILES
        if len(files) == 0:
            return HttpResponseRedirect(reverse("parts:upload_fail"))

        for file_key in files:
            file_obj = files[file_key]
            ext = os.path.splitext(file_obj.name)[1]
            handle_uploaded_file(file_obj, ext)

        return HttpResponseRedirect(reverse("parts:upload_success"))
    return render(request, "parts/upload_file.html")


def upload_success(request):
    return render(request, "parts/upload_success.html")


def upload_fail(request):
    return render(request, "parts/upload_fail.html")


def make_csv(request):
    response = HttpResponse(content_type="text/csv")
    response['Content-Disposition'] = 'attachment;filename="somefilename.csv"'

    writer = csv.writer(response)
    rows = [["Row {} , name=fffffsdfd, age=332, sss".format(idx), str(idx)]
            for idx in range(6305536)]
    for row in rows:
        writer.writerow(row)
    writer.writerow(['First row', 'Foo', 'Bar', 'Baz'])
    writer.writerow(['Second row', 'A', 'B', 'C', '"Testing"', "Here's a quote"])
    return response


class Echo:

    def write(self, value):
        return value


def some_streaming_csv_view(request):

    rows = (["Row {} , name=fffffsdfd, age=332, sss".format(idx),
             str(idx)]
            for idx in range(1065536))

    pseudo_buffer = Echo()
    writer = csv.writer(pseudo_buffer)
    response = StreamingHttpResponse(
        (writer.writerow(row) for row in rows),
        content_type="text/csv")
    response['Content-Disposition'] = 'attachment;filename="somefilename2.csv"'
    return response


def make_csv_by_template(request):
    response = HttpResponse(content_type="text/csv")
    response['Content-Disposition'] = 'attachment;filename="csv_by_template.csv"'
    rows = (
        ("First row", 'Foo', 'Bar', 'Baz'),
        ('Second row', 'A', 'B', 'C', '"Testing"', "Here's a quote")
    )
    # rows = [["Row {} , name=fffffsdfd, age=332, sss".format(idx), str(idx)]
    #         for idx in range(10)]
    t = loader.get_template("csv_template.txt")
    d = dict(data=rows,)
    c = Context(d)
    t_response = t.render(d)
    response.write(t_response)
    return response

mysite/parts/templates/parts/filter_custom.html
{% extends "polls/base.html" %}

{% load parts_filter %}

{% block content %}

<ul>
{% for txt in commodity_list %}
<li>{{ txt|change_str|bold_str|safe }}</li>
{% endfor %}
</ul>


<ul>
{% for txt in commodity_list %}
<li>{{ txt|change_str2:forloop.counter }}</li>
{% endfor %}
</ul>

{{ "?test=1&b=地方&fff=12332>dsf</dsfsdf"|iriencode }}

{% endblock %}

mysite/parts/templates/parts/humanize_view.html
{% extends 'polls/base.html' %}

{% load humanize %}

{% block content %}

{# apnumber 可以对1-9的数字转为英文单词 #}
{{ 1|apnumber }}-{{ 10|apnumber }}-{{ 9|apnumber }}-{{ 999|apnumber }}

<br />

{# intcomma #}
<pre>
{{ 4500|intcomma }}
{{ 4500.2|intcomma }}
{{ 45000|intcomma }}
{{ 450000|intcomma }}
{{ 4500000|intcomma }}
</pre>

<br />
{# intword 用于转化较大的数字为英语单词 #}
<pre>

{{ 0.03|intword }}
{{ 1000000|intword }}
{{ 1200000|intword }}
{{ 12000000000|intword }}
{{ 120000000000000|intword }}
</pre>

<br />
{# naturalday 可以把日期相对于当前日期转为 yesterday, today, tomorrow 其中之一 #}
<pre>
{{ date_now|naturalday }}
{{ date_yesterday|naturalday }}
{{ date_tomorrow|naturalday }}
{{ date_oldday|naturalday }}
</pre>

{# naturaltime #}

<br />
{# ordinal 转为名次的数字表示 #}
<pre>
{{ 1|ordinal }}
{{ 2|ordinal }}
{{ 3|ordinal }}
</pre>
{% endblock %}

mysite/parts/templates/parts/show_filter.html
{% extends 'polls/base.html' %}

{% block content %}

{# add的参数要么是变量名，要么是字符串，字符串的内容必须为整数 #}
{{ age|add:"2"}}   {{age|add:height }}

<br />
{# center以指定的值为字符串的中心位置然后在两侧补足空格达到指定的长度 #}
-{{ name|center:"10" }}-

<br />

{# cut可以把指定的字符替换为空字符串 #}
{{ "我啊!就是没!啥"|cut:"!就" }}

<br />

{# date对日期类型进行格式化。 #}
{{ login_time|date:"Y-m-d H:i:s"  }}

<br />

{# 当变量转为布尔型的值为False。则使用default指定的值输出 #}
{{ v1|default:"xx3232x" }} -{{ v2|default:"xx3232x" }}-{{ v3|default:"xx3232x" }}- {{ name|default:"xx3232x" }}
<br />
{# 当变量为None时。使用default指定的值输出 #}
{{ v1|default_if_none:"xx3232x" }} -{{ v2|default_if_none:"xx3232x" }}


<br />

{# dictsort会以指定列表中元素的指定成员为标准进行排序 #}
{{ user_list|dictsort:"age" }}

<br />
{# safe 可以让模板对html进行转义 #}
{{ polls_index|safe }}

<br />
{# first: 取第一个值, last: 取最后一个值 #}
{{ user_list|first }}-
{{ user_list|last }}

<br />
{# floatformat #}
{# 默认不传参数的话。会精确到小数掉后1位。进行四舍五入运算；若小数位为0.则输出整数位 #}
{{ 34.23234|floatformat }}-{{ 34.0000|floatformat }}-{{ 34.26800|floatformat }}
<br />
{# floatformat 传入参数进行精度控制，并进行四舍五入运算 #}
{{ 34.23234|floatformat:3 }}-{{ 34.0000|floatformat:3 }}-{{ 34.26850|floatformat:3 }}
<br />
{# floatformat传入0把值转换为整数，进行四舍五入运算 #}
{{ 34.23234|floatformat:0 }}-{{ 34.0000|floatformat:"0" }}-{{ 34.86850|floatformat:"0" }}

<br />
{# floatformat传入负数设定小数位精度。若小数位都为0则不保留小数位长度，进行四舍五入运算 #}
{{ 34.23034|floatformat:-3 }}-{{ 34.0000|floatformat:-3 }}-{{ 34.86850|floatformat:-3 }}

<br />
{# join: 使用指定字符串对列表所有的值进行拼接成新的字符串 #}
{{ num_list|join:"--" }}

<br />

{# length: 返回指定变量的长度 #}
{{ num_list|length }}

<br />

{# 大小写转换,lower,upper  #}
{{ "I'm Rock Howard"|lower }}-{{ "I'm Rock Howard"|upper }}-{{ "I'm Rock Howard"|upper|lower }}

<br />

{# random从列表中随机取出一个值返回 #}
{{ num_list|random }}

<br />
{# slice切片 #}
{{ "abcdefg"|slice:"::2" }}

<br />
{# truncatechars 对字符串进行截取到指定长度并以省略号为结尾：可能输出非预期的值 #}
--{{ "abcdefg"|truncatechars:5 }}--

<br />
{# truncatechars_html，忽略html标签，对其中的内容进行指定长度的截取：可能输出非预期的值 #}
--{{ "abcdefg"|truncatechars_html:5 }}--


<br />
{# truncatewords 取指定个数的单词以省略号补充。以空格为依据 #}
--{{ v|truncatewords:3 }}----{{ v4|truncatewords:1 }}--
{{ v5|truncatewords:2 }}
<br />
{# truncatewords_html 会忽略html标签。只处理标签内的文本 #}
{{ v5|truncatewords_html:2 }}

<br />

{# yesno,若变量值为False则返回传入的第二个参数，为True返回第一个参数，为None返回第3个参数，为None且只指定了两个参数。则返回第二个参数 #}

{{ True|yesno:"one,two,three" }}
{{ False|yesno:"one,two,three" }}
{{ None|yesno:"one,two,three" }}
{{ None|yesno:"one,two" }}


{% endblock %}

mysite/parts/templates/parts/tags_custom.html
{% extends "polls/base.html" %}

{% load parts_filter %}

{% block content %}

{{ "abce顶顶顶顶"|bold_str|safe }}

<br />

{% replace_str "123" "2" "aaa" %}

<br />
<div>
{% show_poll_choices question %}
</div>
{% endblock %}

mysite/parts/templates/parts/tags_show_poll_choice.html
<ul>
    {% for choice in choices %}
    <li>{{ choice.id }}-{{ choice.choice_text }}-{{ choice.votes }}</li>
    {% endfor %}
</ul>

mysite/parts/templates/parts/upload_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>upload fail</h1>
    <a href="/parts/upload_file/">跳转回上传页面</a>
</body>
</html>

mysite/parts/templates/parts/upload_file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
     <form action="{% url 'parts:user_upload_file' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        上传文件：<input type="file" name="up_file" />
<input type="file" name="up_file2" />
         <input type="file" name="up_file3" />
        <input id="submit" type="submit" value="上传" />
    </form>
</body>
</html>

mysite/parts/templates/parts/upload_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>upload success</h1>
    <a href="/parts/upload_file/">跳转回上传页面</a>
</body>
</html>